### ISSUE TITLE
Call overreact using Julia 

### ISSUE THREAD

**Issue by Leticia-maria** [geem-lab/overreact#132]
- [x] Overreact.jl
- [ ] Graphical User Interface (Reactive.jl) → Maybe I should implement it online as an API

@schneiderfelipe, please assign me on this issue

~~Deadline: 25/12~~ 

*don't worry about the deadline, @schneiderfelipe, 😂😂 it is only for me. You will be able to check it out after of your summer break.

**Comment by Leticia-maria** [comment]
Correct #31 in Julia Version of Overreact

**Comment by schneiderfelipe** [comment]
I think it would be nice to keep this issue for Overreact.jl and open a separate one for the GUI/API thing (in fact, I think this belongs more to Overreact.jl than to this repo). Let me know what you think.

**Comment by Leticia-maria** [comment]
Overreact.jl is still a private repository in my profile. We can keep this issue open until we fork it to geem-lab. (but you're right)

**Comment by schneiderfelipe** [comment]
Great, I think it's a good solution. I'll create the GUI tag for now then.

**Comment by Leticia-maria** [comment]
@schneiderfelipe Have you seen the Overreact.jl repo?
