### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Leticia-maria** [geem-lab/overreact#150]
- [ ] Check dependabot & GitHub Actions

**Comment by Leticia-maria** [comment]
@schneiderfelipe I think it should be tagged as ```bug``` (IDK if you agree). You can assign me

**Comment by Leticia-maria** [comment]
PyTest is faling; I'm checking it out, @schneiderfelipe 
[logs_369.zip](https://github.com/geem-lab/overreact/files/7872278/logs_369.zip)

**Comment by schneiderfelipe** [comment]
e55ef9f didn't work 😆

**Comment by Leticia-maria** [comment]
This is useless. I will close the issue, @schneiderfelipe.
